model:
  class_path: datasets.custom_task.CustomSemanticSegmentationTask
  init_args:
    model: "unet"
    backbone: "resnet18"
    weights: true
    in_channels: 3
    num_classes: 3
    loss: "ce"
    lr: 1e-3
    tmax: 50

data:
  class_path: datasets.kabul_informal_settlement_datamodule.KabulInformalSettlementDatamodule
  init_args:
    batch_size: 16
    root: "C:/Users/esmat/Desktop/Master Dataset - TorchGeo"

trainer:
  max_epochs: 3
  accelerator: "gpu"
  devices: 1
  precision: 32
  log_every_n_steps: 10
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: lightning_logs
      name: torchgeo
